#!/bin/bash

echo "installing programs"
if [[ $(uname) == "Linux" ]]; then
   programs="zsh curl wget tmux vim neovim mosh python3-pip bat"
   which apt && \
      sudo apt install -y $programs
   which pacman && \
      sudo pacman -Syu $programs
elif [[ $(uname) == "Darwin" ]]; then
   brew install zsh git tmux vim neovim coreutils mosh python urlview fpp \
      reattach-to-user-namespace bat gnupg
fi


if [[ ! -e $HOME/.antigen ]]; then
   echo "bootstrapping antigen"
   git clone https://github.com/zsh-users/antigen.git $HOME/.antigen
fi


if [[ ! -e $HOME/.tmux/plugins/tpm ]]; then
   echo "bootstrapping tmux"
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
   ~/.tmux/plugins/tpm/bin/install_plugins
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugInstall!' '+PlugClean!' '+PlugUpdate!' '+qall'
fi


if [[ ! -e $HOME/.iterm2_shell_integration.zsh ]]; then
   echo "bootstrapping iterm2 shell integration"
   curl -L https://iterm2.com/shell_integration/zsh \
   -o ~/.iterm2_shell_integration.zsh
fi

chsh -s $(which zsh) && zsh

