#!/bin/bash

echo "installing programs"
if [[ $(uname) == "Linux" ]]; then
   sudo apt install -y zsh git tmux vim neovim sshfs mosh
elif [[ $(uname) == "Darwin" ]]; then
   brew install zsh git tmux vim neovim coreutils sshf mosh
fi

echo "bootstrapping antigen"
if [[ ! -e $HOME/.antigen ]]; then
   git clone https://github.com/zsh-users/antigen.git $HOME/.antigen
fi

echo "bootstrapping tmux"
if [[ ! -e $HOME/.tmux/plugins/tpm ]]; then
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
   ~/.tmux/plugins/tpm/bin/install_plugins
fi

chsh -s $(which zsh) && zsh


