#!/bin/bash

if [[ $(uname) == "Linux" ]]; then
   sudo apt install zsh git tmux vim
elif [[ $(uname) == "Darwin" ]]; then
   brew install zsh git tmux vim
fi


if [[ ! -e $HOME/.antigen ]]; then
   git clone https://github.com/zsh-users/antigen.git $HOME/.antigen
fi

if [[ ! -e $HOME/.tmux/plugins/tpm ]]; then
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

chsh -s $(which zsh) && zsh

echo "Log out and log back in!"

